/**
 * Codegen / introspection entry points (CLI wired later via Studio).
 */

export type IntrospectionSnapshot = {
    readonly dialect: "postgres" | "mysql" | "sqlite";
    readonly tables: readonly {
        name: string;
        columns: readonly {
            name: string;
            sqlType: string;
            nullable: boolean;
            isPrimaryKey: boolean;
            isGenerated: boolean;
        }[];
    }[];
};

/** Emit a Database interface TypeScript source from an introspection snapshot. */
export function generateDatabaseTypes(snapshot: IntrospectionSnapshot): string {
    const lines: string[] = [
        "/* Generated by @yydb/sql-studio-orm/codegen — do not hand-edit. */",
        'import type { Generated } from "@yydb/sql-studio-orm";',
        "",
        "export interface Database {",
    ];
    for (const table of snapshot.tables) {
        const iface = `${pascal(table.name)}Table`;
        lines.push(`  ${table.name}: ${iface};`);
    }
    lines.push("}", "");

    for (const table of snapshot.tables) {
        lines.push(`export interface ${pascal(table.name)}Table {`);
        for (const col of table.columns) {
            const ts = sqlTypeToTs(col.sqlType, col.nullable);
            const typed = col.isGenerated ? `Generated<${ts}>` : ts;
            lines.push(`  ${col.name}: ${typed};`);
        }
        lines.push("}", "");
    }
    return lines.join("\n");
}

function pascal(name: string): string {
    return name
        .split(/[_\s]+/)
        .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
        .join("");
}

function sqlTypeToTs(sqlType: string, nullable: boolean): string {
    const t = sqlType.toLowerCase();
    let base = "unknown";
    if (t.includes("int") || t.includes("numeric") || t.includes("decimal") || t.includes("float") || t.includes("double")) {
        base = "number";
    } else if (t.includes("bool")) {
        base = "boolean";
    } else if (t.includes("json")) {
        base = "unknown";
    } else if (t.includes("char") || t.includes("text") || t.includes("uuid") || t.includes("string")) {
        base = "string";
    } else if (t.includes("timestamp") || t.includes("date") || t.includes("time")) {
        base = "Date";
    }
    return nullable ? `${base} | null` : base;
}

export async function pullSchema(_options: { dialect: "postgres" | "mysql" | "sqlite"; url: string }): Promise<IntrospectionSnapshot> {
    throw new Error("@yydb/sql-studio-orm/codegen: pullSchema not implemented yet");
}
